name=Pala
version=0.1.0
author=Emmanuel Enrique Cardeña Bojorquez <emmanuel.cardena@cecyteqroo.edu.mx>
maintainer=Emmanuel Enrique Cardeña Bojorquez <emmanuel.cardena@cecyteqroo.edu.mx>
sentence=Una libreria para controlar una pala con un servoMotor.
paragraph=Esta libreria permite mover una pala con un servomotor de dos posiciones 0 y 180.
category=Device Control
url=https://github.com
architectures=*
